### ISSUE TITLE
Register page implementation

### ISSUE THREAD

**Issue by DevMatheusSilva** [DevMatheusSilva/Planner-ts-api-crud#4]
# Objective
Implement the user register page for application

# Tasks
- [ ] Implement template html in ejs
- [ ] Stylize the page with css
- [ ] Create the routes
- [ ] Implement Controller
- [ ] Implement Service
- [ ] Implement Repository (In memory by now)
